### ISSUE TITLE
bro what the fuck is a "signautre"???

### ISSUE THREAD

**Issue by nay-cat** [spokwn/prefetch-parser#1]
parses windows prefetch files, analyzing digital signautres, and also generics, with lots of features.

spok tu madre es una ballena

**Comment by spokwn** [comment]
Example of a "digital signature": https://imgur.com/8gvSDCm

chatgpt bc you may need it:
On Windows, digital signatures for `.exe` files verify the file's authenticity and integrity by ensuring it originates from a trusted source and hasn't been tampered with. Developers use a code signing certificate to sign the file, embedding a cryptographic hash and certificate details. When executed, Windows checks the signature against trusted Certificate Authorities (CAs), alerting users if it's invalid or modified. Signed `.exe` files display the publisher's name, reassuring users and bypassing security warnings like SmartScreen. Tools like Microsoft's SignTool enable signing, and users can verify signatures via File Explorer or command-line utilities to ensure software safety.

**Comment by nay-cat** [comment]
te intentaste hacer el listo y no sabes escribir petardo (jk)
